### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by blvz** [fffixed/vue-bus#3]
https://github.com/fffixed/vue-bus/blob/c2749aa9445a4cef2ede977bad800116df43e2da/vue-bus.js#L36

Example: https://jsfiddle.net/1zz9snkv/

**Comment by fffixed** [comment]
Jesus! You're really right bro! It's my big mistake!

**Comment by blvz** [comment]
No problem, mate. 😉
I did a implementation myself, if you wanna copy it:

```js
Vue.mixin({
  created () {
    if (!this.$options.$bus) return
    this.$busListeners = { }

    Object.keys(this.$options.$bus).forEach(name => {
      if (typeof this.$options.$bus[name] !== 'function') {
        throw new Error(name + ' is not a function.')
      }

      const fn = this.$options.$bus[name].bind(this)
      this.$busListeners[name] = fn
      bus.$on(name, fn)
    })
  },

  beforeDestroy () {
    if (!this.$options.$bus) return

    Object.keys(this.$options.$bus).forEach(name => {
      const fn = this.$busListeners[name]
      bus.$off(name, fn)
    })

    delete this.$busListeners
  }
})
```

**EDIT**: oops, updated the above. I think it's better to store the listeners in a separate, `$busListeners` object, to avoid conflicts with component's events.

**Comment by fffixed** [comment]
Tnx, Rafael, I fixed it :+1:
